# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a3a8edd-b4b9-4f17-87ea-b4d1e355e41a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B0B-5A57";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e780f0c2-ce72-4497-87c6-9dac5f45d555";
      fsType = "ext4";
    };

  fileSystems."/media/backup" =
    { device = "/dev/disk/by-uuid/50353c11-beed-4c9c-8432-bbf608e989e4";
      fsType = "ext4";
    };

  fileSystems."/media/Media" =
    { device = "/dev/disk/by-uuid/30DC85B7DC85783C";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  fileSystems."/media/TV" =
    { device = "/dev/disk/by-uuid/9C08911F0890FA0A";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
